name: Continuous Integration

on:
  pull_request:
    branches:
      - develop
      - alpha 
      - main

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1
      
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
          bundler-cache: true

      - name: Install node modules
        run: |
          yarn install
      - name: Run CI with Lefthook
        run: |
          yarn lefthook run ci-hook
      
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android App Bundle
        run: |
          cd android && ./gradlew bundleRelease --no-daemon

      - name: Deploy Android Beta to App Distribution via Fastlane
        run: bundle exec fastlane android beta

